/**
 * Pre-register all icons used by the app so they render offline.
 *
 * `icon-bundle.json` is generated by `scripts/extract-icons.mjs` and contains
 * only the ~320 icons referenced in `../icons.ts` (~120 KB vs ~9 MB for full
 * collections).  The `iconify-icon` web component checks its local cache first;
 * registered icons never hit the CDN.
 *
 * Regenerate after editing icons.ts:  node scripts/extract-icons.mjs
 */
import { addIcon } from 'iconify-icon';
import bundle from './icon-bundle.json';

export function registerIcons() {
  for (const [name, data] of Object.entries(bundle)) {
    addIcon(name, data as { body: string; width: number; height: number });
  }
}
