#!/usr/bin/env node

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { versions } from "./docs-versions.mjs";

function walkFiles(directory) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const target = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(target));
    } else if (entry.isFile()) {
      files.push(target);
    }
  }
  return files;
}

function toRouteSegments(file, root) {
  return relative(root, file)
    .split(sep)
    .map((segment) => segment.replace(/\.(?:md|mdx|tsx)$/u, ""))
    .filter((segment) => segment !== "page" && segment !== "index")
    .filter((segment) => !(segment.startsWith("(") && segment.endsWith(")")));
}

export function collectAnalyticsRoutes({ webRoot, repoRoot }) {
  const resolvedWebRoot = fileURLToPath(webRoot);
  const resolvedRepoRoot = fileURLToPath(repoRoot);
  const appRoot = join(resolvedWebRoot, "src", "app");
  const routes = new Set();

  for (const file of walkFiles(appRoot)) {
    if (!file.endsWith(`${sep}page.tsx`)) {
      continue;
    }
    const segments = toRouteSegments(file, appRoot);
    if (segments.some((segment) => segment.includes("[") || segment.includes("]"))) {
      continue;
    }
    routes.add(segments.length === 0 ? "/" : `/${segments.join("/")}`);
  }

  for (const version of versions) {
    const sourceRoot = join(resolvedRepoRoot, "content", "docs", version.source);
    for (const file of walkFiles(sourceRoot)) {
      if (![".md", ".mdx"].includes(extname(file))) {
        continue;
      }
      const segments = toRouteSegments(file, sourceRoot);
      const suffix = segments.length === 0 ? "" : `/${segments.join("/")}`;
      routes.add(`/docs/${version.slug}${suffix}`);
    }
  }

  routes.add(`/docs/${versions[0].slug}/changelog`);

  return [...routes].sort();
}

export function renderAnalyticsRouteManifest(routes) {
  const values = routes.map((route) => `  ${JSON.stringify(route)},`).join("\n");
  return `// Generated by scripts/analytics-routes.mjs. Do not edit by hand.\nconst routes = [\n${values}\n] as const;\n\nexport const ANALYTICS_ROUTES: ReadonlySet<string> = new Set(routes);\n`;
}

function run() {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const webRoot = pathToFileURL(join(scriptDir, "..", sep));
  const repoRoot = pathToFileURL(join(scriptDir, "..", "..", "..", sep));
  const target = join(scriptDir, "..", "src", "lib", "analytics-routes.generated.ts");
  const expected = renderAnalyticsRouteManifest(collectAnalyticsRoutes({ webRoot, repoRoot }));

  if (process.argv.includes("--check")) {
    if (!existsSync(target) || readFileSync(target, "utf8") !== expected) {
      console.error("Analytics route manifest is stale. Run: npm run sync:analytics-routes");
      process.exitCode = 1;
    }
    return;
  }

  writeFileSync(target, expected);
  console.log(`Generated ${target}`);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  run();
}
