import type { AuditEntry } from '../../../app/model/audit.js';

const backendAuditActions = {
  'update-available': true,
  'update-applied': true,
  'update-applied-dryrun': true,
  'update-failed': true,
  'notification-delivery-failed': true,
  'container-update': true,
  'security-alert': true,
  'security-scan-skipped': true,
  'scanner-asset-pull-started': true,
  'scanner-asset-pull-succeeded': true,
  'scanner-asset-pull-failed': true,
  'scanner-asset-warm-started': true,
  'scanner-asset-warm-succeeded': true,
  'scanner-asset-warm-failed': true,
  'agent-disconnect': true,
  'container-unhealthy': true,
  'maturity-cleared': true,
  'container-added': true,
  'container-removed': true,
  rollback: true,
  preview: true,
  'container-start': true,
  'container-stop': true,
  'container-restart': true,
  'webhook-watch': true,
  'webhook-watch-container': true,
  'webhook-update': true,
  'hook-configured': true,
  'hook-pre-success': true,
  'hook-pre-failed': true,
  'hook-post-success': true,
  'hook-post-failed': true,
  'auto-rollback': true,
  'auth-login': true,
  'env-reveal': true,
  'debug-dump': true,
  'config-read': true,
  'config-validated': true,
  'config-reloaded': true,
  'config-written': true,
  'auto-update-blocked': true,
  'update-policy-override-set': true,
  'update-policy-override-cleared': true,
  'update-approved': true,
  'update-rejected': true,
  'update-deferred': true,
  'mqtt-command-update': true,
  'api-key-created': true,
  'api-key-revoked': true,
  'api-key-auth-failed': true,
  'image-prune': true,
} satisfies Record<AuditEntry['action'], true>;

export const BACKEND_AUDIT_ACTIONS = Object.keys(backendAuditActions);
