import type { InjectionKey, Ref } from 'vue';
import { inject } from 'vue';

export interface ContainersViewTemplateContext {
  error: unknown;
  loading: unknown;
  containers: unknown;
  containerViewMode: unknown;
  showFilters: unknown;
  filteredContainers: unknown;
  activeFilterCount: unknown;
  filterSearch: Ref<string>;
  filterStatus: unknown;
  filterBouncer: unknown;
  filterRegistry: unknown;
  filterServer: unknown;
  serverNames: unknown;
  filterKind: unknown;
  clearFilters: unknown;
  showColumnPicker: unknown;
  toggleColumnPicker: unknown;
  columnPickerStyle: unknown;
  allColumns: unknown;
  toggleColumn: unknown;
  visibleColumns: unknown;
  tt: unknown;
  groupByStack: unknown;
  rechecking: unknown;
  recheckAll: unknown;
  renderGroups: unknown;
  toggleGroupCollapse: unknown;
  collapsedGroups: unknown;
  groupUpdateInProgress: unknown;
  actionInProgress: unknown;
  updateAllInGroup: unknown;
  tableColumns: unknown;
  containerSortKey: unknown;
  containerSortAsc: unknown;
  selectedContainer: unknown;
  isCompact: unknown;
  selectContainer: unknown;
  tableActionStyle: unknown;
  openActionsMenu: unknown;
  toggleActionsMenu: unknown;
  updateContainer: (containerName: string) => Promise<void>;
  confirmStop: unknown;
  startContainer: unknown;
  confirmRestart: unknown;
  scanContainer: unknown;
  confirmForceUpdate: unknown;
  skipUpdate: unknown;
  closeActionsMenu: unknown;
  confirmDelete: unknown;
  displayContainers: unknown;
  actionsMenuStyle: unknown;
  updateKindColor: unknown;
  hasRegistryError: unknown;
  registryErrorTooltip: unknown;
  containerPolicyTooltip: unknown;
  getContainerListPolicyState: unknown;
  serverBadgeColor: unknown;
  parseServer: unknown;
  registryColorBg: unknown;
  registryColorText: unknown;
  registryLabel: unknown;
  detailPanelOpen: unknown;
  isMobile: unknown;
  panelSize: unknown;
  closePanel: unknown;
  openFullPage: unknown;
  detailTabs: Array<{ id: string; label: string; icon: string }>;
  activeDetailTab: unknown;
  selectedRuntimeOrigins: unknown;
  runtimeOriginStyle: unknown;
  runtimeOriginLabel: unknown;
  selectedRuntimeDriftWarnings: unknown;
  selectedLifecycleHooks: unknown;
  lifecycleHookTemplateVariables: unknown;
  selectedAutoRollbackConfig: unknown;
  selectedImageMetadata: unknown;
  formatTimestamp: unknown;
  detailVulnerabilityLoading: unknown;
  detailSbomLoading: unknown;
  loadDetailSecurityData: unknown;
  detailVulnerabilityError: unknown;
  vulnerabilitySummary: unknown;
  vulnerabilityTotal: unknown;
  vulnerabilityPreview: unknown;
  severityStyle: unknown;
  normalizeSeverity: unknown;
  getVulnerabilityPackage: unknown;
  selectedSbomFormat: unknown;
  loadDetailSbom: unknown;
  detailSbomError: unknown;
  sbomDocument: unknown;
  sbomComponentCount: unknown;
  sbomGeneratedAt: unknown;
  LOG_AUTO_FETCH_INTERVALS: unknown;
  containerAutoFetchInterval: unknown;
  getContainerLogs: unknown;
  containerLogRef: unknown;
  containerHandleLogScroll: unknown;
  containerScrollBlocked: unknown;
  containerResumeAutoScroll: unknown;
  previewLoading: unknown;
  runContainerPreview: unknown;
  policyInProgress: unknown;
  skipCurrentForSelected: unknown;
  snoozeSelected: unknown;
  snoozeDateInput: unknown;
  snoozeSelectedUntilDate: unknown;
  selectedSnoozeUntil: unknown;
  unsnoozeSelected: unknown;
  selectedSkipTags: unknown;
  selectedSkipDigests: unknown;
  clearSkipsSelected: unknown;
  selectedUpdatePolicy: unknown;
  clearPolicySelected: unknown;
  policyMessage: unknown;
  policyError: unknown;
  removeSkipTagSelected: unknown;
  removeSkipDigestSelected: unknown;
  detailPreview: unknown;
  previewError: unknown;
  triggersLoading: unknown;
  detailTriggers: unknown;
  getTriggerKey: unknown;
  triggerRunInProgress: unknown;
  runAssociatedTrigger: unknown;
  triggerMessage: unknown;
  triggerError: unknown;
  backupsLoading: unknown;
  detailBackups: unknown;
  rollbackInProgress: unknown;
  rollbackToBackup: unknown;
  rollbackMessage: unknown;
  rollbackError: unknown;
  updateOperationsLoading: unknown;
  detailUpdateOperations: unknown;
  getOperationStatusStyle: unknown;
  formatOperationStatus: unknown;
  formatOperationPhase: unknown;
  formatRollbackReason: unknown;
  updateOperationsError: unknown;
  closeFullPage: unknown;
}

export const containersViewTemplateContextKey: InjectionKey<ContainersViewTemplateContext> = Symbol(
  'containers-view-template-context',
);

export function useContainersViewTemplateContext(): ContainersViewTemplateContext {
  const context = inject(containersViewTemplateContextKey);
  if (!context) {
    throw new Error('ContainersView template context is not available');
  }
  return context;
}
