#!/usr/bin/env node
/**
 * gen-banner.mjs — Build-time generator for the startup banner art.
 *
 * Reads drydock.png from the repo root, samples it via ImageMagick 7,
 * and writes app/banner/art.ts with a baked 24-bit truecolor half-block
 * string.  Run manually like scripts/regenerate-brand-assets.sh.
 *
 *   node scripts/gen-banner.mjs
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const PNG = resolve(ROOT, 'drydock.png');
const OUT = resolve(ROOT, 'app/banner/art.ts');

const TARGET_WIDTH = 50;

// ESC character as a string constant so biome doesn't flag a control-char regex literal.
const ESC = String.fromCharCode(27);
const RESET = `${ESC}[0m`;

// ---------------------------------------------------------------------------
// 1. Dump pixels via ImageMagick
// ---------------------------------------------------------------------------
const raw = execSync(`magick ${PNG} -resize ${TARGET_WIDTH}x -depth 8 txt:-`, {
  encoding: 'utf8',
  maxBuffer: 10 * 1024 * 1024,
});

// Parse header: "# ImageMagick pixel enumeration: W,H,..."
const headerMatch = raw.match(/^# ImageMagick pixel enumeration: (\d+),(\d+)/m);
if (!headerMatch) {
  throw new Error('Could not parse ImageMagick header');
}
const imgW = Number.parseInt(headerMatch[1], 10);
const imgH = Number.parseInt(headerMatch[2], 10);

// Build 2-D array of {r,g,b,a}
const pixels = Array.from({ length: imgH }, () =>
  Array.from({ length: imgW }, () => ({ r: 0, g: 0, b: 0, a: 0 })),
);

for (const line of raw.split('\n')) {
  // "x,y: (r,g,b,a)  #..."
  const m = line.match(/^(\d+),(\d+):\s*\((\d+),(\d+),(\d+),(\d+)\)/);
  if (!m) continue;
  const x = Number.parseInt(m[1], 10);
  const y = Number.parseInt(m[2], 10);
  if (x < imgW && y < imgH) {
    pixels[y][x] = {
      r: Number.parseInt(m[3], 10),
      g: Number.parseInt(m[4], 10),
      b: Number.parseInt(m[5], 10),
      a: Number.parseInt(m[6], 10),
    };
  }
}

// ---------------------------------------------------------------------------
// 2. Render half-block rows
// ---------------------------------------------------------------------------
const charRows = [];
const numCharRows = Math.ceil(imgH / 2);

for (let row = 0; row < numCharRows; row++) {
  const topY = row * 2;
  const botY = row * 2 + 1;
  let line = '';

  for (let x = 0; x < imgW; x++) {
    const top = pixels[topY]?.[x] ?? { r: 0, g: 0, b: 0, a: 0 };
    const bot = pixels[botY]?.[x] ?? { r: 0, g: 0, b: 0, a: 0 };
    const topOpaque = top.a >= 128;
    const botOpaque = bot.a >= 128;

    if (!topOpaque && !botOpaque) {
      // Both transparent: plain space with reset
      line += `${RESET} `;
    } else if (topOpaque && !botOpaque) {
      // Top only: upper-half block in fg
      line += `${RESET}${ESC}[38;2;${top.r};${top.g};${top.b}m▀`;
    } else if (!topOpaque && botOpaque) {
      // Bottom only: lower-half block in fg
      line += `${RESET}${ESC}[38;2;${bot.r};${bot.g};${bot.b}m▄`;
    } else {
      // Both opaque: upper-half block, fg=top, bg=bot
      line += `${ESC}[38;2;${top.r};${top.g};${top.b};48;2;${bot.r};${bot.g};${bot.b}m▀`;
    }
  }

  line += RESET;
  charRows.push(line);
}

// ---------------------------------------------------------------------------
// 3. Trim fully-blank leading/trailing lines
//    "Blank" = line contains only spaces and reset sequences
// ---------------------------------------------------------------------------
// Build ANSI-strip regex dynamically so biome doesn't flag a control-char literal.
const ANSI_RE = new RegExp(`${ESC}\\[[0-9;]*m`, 'g');

function isBlankLine(line) {
  return line.replace(ANSI_RE, '').trim() === '';
}

let start = 0;
let end = charRows.length - 1;
while (start <= end && isBlankLine(charRows[start])) start++;
while (end >= start && isBlankLine(charRows[end])) end--;
const trimmed = charRows.slice(start, end + 1);

// ---------------------------------------------------------------------------
// 4. Write art.ts
// ---------------------------------------------------------------------------
// Escape the art string for embedding in a TS single-quoted string literal.
// ESC chars become \x1b escape sequences; newlines become \n.
const artJoined = trimmed.join('\n');

// Build the escape regex dynamically to avoid biome flagging control-char literals.
const ESC_RE = new RegExp(ESC, 'g');
const artEscaped = artJoined
  .replace(/\\/g, '\\\\')
  .replace(/'/g, "\\'")
  .replace(ESC_RE, '\\x1b')
  .replace(/\n/g, '\\n');

const bannerWidth = imgW;

const tsContent = `// AUTO-GENERATED by scripts/gen-banner.mjs — do not edit manually.
export const BANNER_ART = '${artEscaped}';
export const BANNER_WIDTH = ${bannerWidth};
`;

writeFileSync(OUT, tsContent, 'utf8');

// ---------------------------------------------------------------------------
// 5. Lint/format the generated file
// ---------------------------------------------------------------------------
try {
  execSync(`npx @biomejs/biome check --write ${OUT}`, {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: 'pipe',
  });
} catch {
  // biome may exit non-zero if it had to fix things; that's fine.
}

console.log(`Banner generated: ${trimmed.length} lines, ${bannerWidth} cells wide -> ${OUT}`);
