import { execFileSync } from 'node:child_process';
import { appendFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

function runBranch({ repo, base, runId, attempt }) {
  if (!/^[\w.-]+\/[\w.-]+$/.test(repo ?? '')) throw new Error('Invalid repository');
  if (!/^dev\/v\d+\.\d+$/.test(base ?? '')) throw new Error('Expected a dev branch');
  if (!/^\d+$/.test(runId ?? '') || !/^\d+$/.test(attempt ?? '')) {
    throw new Error('Invalid workflow run coordinates');
  }
  return `starchart/${base.replace('/', '-')}/${runId}-${attempt}`;
}

function validateSha(sha) {
  if (!/^[a-f0-9]{40}$/.test(sha ?? '')) throw new Error('Invalid commit SHA');
  return sha;
}

export async function prepareChartBranch(api, options) {
  const branch = runBranch(options);
  const prefix = `/repos/${options.repo}`;
  const ref = await api('GET', `${prefix}/git/ref/heads/${options.base}`);
  const baseSha = validateSha(ref.object?.sha);
  await api('POST', `${prefix}/git/refs`, { ref: `refs/heads/${branch}`, sha: baseSha });
  const created = await api('GET', `${prefix}/git/ref/heads/${branch}`);
  if (created.object?.sha !== baseSha) throw new Error('Unexpected created branch SHA');
  return { branch, baseSha };
}

export async function publishChartPr(api, options) {
  const { repo, base, branch, baseSha } = options;
  if (branch !== runBranch(options)) throw new Error('Unexpected run branch');
  validateSha(baseSha);
  const prefix = `/repos/${repo}`;
  const ref = await api('GET', `${prefix}/git/ref/heads/${branch}`);
  const headSha = validateSha(ref.object?.sha);
  const comparison = await api('GET', `${prefix}/compare/${baseSha}...${headSha}`);
  if (!['ahead', 'identical'].includes(comparison.status)) {
    throw new Error('Unexpected generated branch history');
  }
  const allowed = new Set(['docs/assets/star-history.svg', 'docs/assets/star-history-dark.svg']);
  const files = comparison.files;
  if (
    !Array.isArray(files) ||
    files.length > 2 ||
    files.some((file) => !allowed.has(file.filename) || file.status !== 'modified')
  ) {
    throw new Error('Generated diff must contain only modified chart SVGs');
  }
  if (files.length === 0) {
    await api('DELETE', `${prefix}/git/refs/heads/${branch}`);
    return null;
  }
  const query = new URLSearchParams({
    state: 'open',
    head: `${repo.split('/')[0]}:${branch}`,
    base,
  });
  const existing = await api('GET', `${prefix}/pulls?${query}`);
  const pr =
    existing[0] ??
    (await api('POST', `${prefix}/pulls`, {
      title: 'chore(docs): refresh the star-history charts',
      head: branch,
      base,
      body: 'Refresh the committed light and dark star-history charts. Generated by the pinned Starchart workflow. Normal review and required checks apply.',
    }));
  const verified = await api('GET', `${prefix}/pulls/${pr.number}`);
  if (
    verified.state !== 'open' ||
    verified.head?.ref !== branch ||
    verified.head?.sha !== headSha ||
    verified.base?.ref !== base
  ) {
    throw new Error('Created PR does not match the verified chart branch');
  }
  return verified.html_url;
}

function githubApi(method, path, body) {
  const args = ['api', '--method', method, path];
  if (body !== undefined) args.push('--input', '-');
  const output = execFileSync('gh', args, {
    encoding: 'utf8',
    input: body === undefined ? undefined : JSON.stringify(body),
    timeout: 60_000,
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  return output.trim() ? JSON.parse(output) : undefined;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.env.GITHUB_REF_TYPE !== 'branch') throw new Error('Expected a branch dispatch');
  const options = {
    repo: process.env.GITHUB_REPOSITORY,
    base: process.env.TARGET_BRANCH,
    runId: process.env.GITHUB_RUN_ID,
    attempt: process.env.CHART_RUN_ATTEMPT ?? process.env.GITHUB_RUN_ATTEMPT,
    branch: process.env.CHART_BRANCH,
    baseSha: process.env.CHART_BASE_SHA,
  };
  if (process.argv[2] === 'prepare') {
    const { branch, baseSha } = await prepareChartBranch(githubApi, options);
    appendFileSync(
      process.env.GITHUB_OUTPUT,
      `branch=${branch}\nbase-sha=${baseSha}\nrun-attempt=${options.attempt}\n`,
    );
  } else if (process.argv[2] === 'publish') {
    const url = await publishChartPr(githubApi, options);
    console.log(url ?? 'Chart unchanged; removed the temporary branch.');
  } else {
    throw new Error('Expected prepare or publish');
  }
}
