import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import test from 'node:test';

import { prepareChartBranch, publishChartPr } from './starchart-pr.mjs';

const baseSha = 'a'.repeat(40);
const headSha = 'b'.repeat(40);
const options = { repo: 'CodesWhat/drydock', base: 'dev/v1.8', runId: '123', attempt: '2' };
const branch = 'starchart/dev-v1.8/123-2';
const prefix = '/repos/CodesWhat/drydock';
const chartFiles = ['docs/assets/star-history.svg', 'docs/assets/star-history-dark.svg'];

function client(responses) {
  const calls = [];
  return {
    calls,
    api: async (method, path, body) => {
      calls.push({ method, path, body });
      assert.ok(responses.length > 0, `unexpected ${method} ${path}`);
      const response = responses.shift();
      if (response instanceof Error) throw response;
      return response;
    },
  };
}

test('prepare creates only a run-scoped branch from the current dev head', async () => {
  const { api, calls } = client([
    { object: { sha: baseSha } },
    { object: { sha: baseSha } },
    { object: { sha: baseSha } },
  ]);
  assert.deepEqual(await prepareChartBranch(api, options), { branch, baseSha });
  assert.deepEqual(calls, [
    { method: 'GET', path: `${prefix}/git/ref/heads/dev/v1.8`, body: undefined },
    {
      method: 'POST',
      path: `${prefix}/git/refs`,
      body: { ref: `refs/heads/${branch}`, sha: baseSha },
    },
    { method: 'GET', path: `${prefix}/git/ref/heads/${branch}`, body: undefined },
  ]);
});

for (const base of [
  'main',
  'master',
  'v1.8.0',
  'refs/heads/dev/v1.8',
  'dev/v1.8\nmain',
  'dev/v1.8/extra',
]) {
  test(`prepare rejects non-dev target ${JSON.stringify(base)} before any API call`, async () => {
    const { api, calls } = client([]);
    await assert.rejects(prepareChartBranch(api, { ...options, base }), /dev branch/);
    assert.equal(calls.length, 0);
  });
}

test('prepare refuses invalid run coordinates and malformed GitHub SHAs', async () => {
  const { api, calls } = client([]);
  await assert.rejects(prepareChartBranch(api, { ...options, runId: '../123' }), /run/);
  assert.equal(calls.length, 0);
  await assert.rejects(
    prepareChartBranch(client([{ object: { sha: 'bad' } }]).api, options),
    /SHA/,
  );
});

test('prepare propagates a failed branch creation without pretending it exists', async () => {
  const { api } = client([{ object: { sha: baseSha } }, new Error('422 branch exists')]);
  await assert.rejects(prepareChartBranch(api, options), /422/);
});

function publicationResponses(
  files = chartFiles.map((filename) => ({ filename, status: 'modified' })),
) {
  return [
    { object: { sha: headSha } },
    { status: 'ahead', files },
    [],
    { number: 42 },
    {
      state: 'open',
      head: { ref: branch, sha: headSha },
      base: { ref: options.base },
      html_url: 'https://github.com/CodesWhat/drydock/pull/42',
    },
  ];
}

test('publish validates the immutable generated diff and opens a verified PR into its dev branch', async () => {
  const { api, calls } = client(publicationResponses());
  assert.equal(
    await publishChartPr(api, { ...options, branch, baseSha }),
    'https://github.com/CodesWhat/drydock/pull/42',
  );
  assert.equal(calls[1].path, `${prefix}/compare/${baseSha}...${headSha}`);
  assert.deepEqual(calls[3].body, {
    title: 'chore(docs): refresh the star-history charts',
    head: branch,
    base: options.base,
    body: 'Refresh the committed light and dark star-history charts. Generated by the pinned Starchart workflow. Normal review and required checks apply.',
  });
  assert.equal(calls[4].path, `${prefix}/pulls/42`);
  assert.ok(calls.every((call) => call.method !== 'PATCH' && call.method !== 'DELETE'));
});

test('publish accepts a change to either chart when the sibling is unchanged', async () => {
  const { api } = client(publicationResponses([{ filename: chartFiles[0], status: 'modified' }]));
  await publishChartPr(api, { ...options, branch, baseSha });
});

for (const files of [
  [{ filename: 'README.md', status: 'modified' }],
  [{ filename: chartFiles[0], status: 'removed' }],
  [{ filename: chartFiles[0], status: 'renamed', previous_filename: 'other.svg' }],
  [{ filename: chartFiles[0], status: 'added' }],
  undefined,
]) {
  test(`publish refuses unexpected output ${JSON.stringify(files)}`, async () => {
    const { api, calls } = client([{ object: { sha: headSha } }, { status: 'ahead', files }]);
    await assert.rejects(publishChartPr(api, { ...options, branch, baseSha }), /chart/);
    assert.equal(calls.length, 2);
  });
}

test('unchanged charts delete only this run branch and create no PR', async () => {
  const { api, calls } = client([
    { object: { sha: baseSha } },
    { status: 'identical', files: [] },
    undefined,
  ]);
  assert.equal(await publishChartPr(api, { ...options, branch, baseSha }), null);
  assert.deepEqual(calls[2], {
    method: 'DELETE',
    path: `${prefix}/git/refs/heads/${branch}`,
    body: undefined,
  });
});

test('a rerun reuses and verifies the existing PR instead of opening another', async () => {
  const responses = publicationResponses();
  responses.splice(2, 2, [{ number: 42 }]);
  const { api, calls } = client(responses);
  await publishChartPr(api, { ...options, branch, baseSha });
  assert.ok(calls.every((call) => call.method === 'GET'));
});

test('publish rejects a substituted run branch before any API call', async () => {
  const { api, calls } = client([]);
  await assert.rejects(
    publishChartPr(api, { ...options, branch: 'dev/v1.8', baseSha }),
    /run branch/,
  );
  assert.equal(calls.length, 0);
});

test('publish refuses divergent history even when only chart files changed', async () => {
  const responses = publicationResponses();
  responses[1].status = 'diverged';
  const { api, calls } = client(responses);
  await assert.rejects(publishChartPr(api, { ...options, branch, baseSha }), /history/);
  assert.equal(calls.length, 2);
});

test('publish propagates PR creation failure and preserves the generated branch', async () => {
  const responses = publicationResponses();
  responses[3] = new Error('403 denied');
  const { api, calls } = client(responses);
  await assert.rejects(publishChartPr(api, { ...options, branch, baseSha }), /403/);
  assert.ok(calls.every((call) => call.method !== 'DELETE'));
});

test('publish refuses to report success if the fetched PR head changed', async () => {
  const responses = publicationResponses();
  responses[4].head.sha = baseSha;
  await assert.rejects(
    publishChartPr(client(responses).api, { ...options, branch, baseSha }),
    /PR/,
  );
});

function cli(t, mode, responses, extraEnv = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'drydock-chart-cli-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const log = join(dir, 'calls.json');
  const output = join(dir, 'outputs');
  writeFileSync(log, '[]');
  writeFileSync(join(dir, 'responses.json'), JSON.stringify(responses));
  writeFileSync(
    join(dir, 'gh'),
    `#!${process.execPath}
const fs = require('node:fs');
const log = process.env.CHART_TEST_LOG;
const calls = JSON.parse(fs.readFileSync(log, 'utf8'));
const responses = JSON.parse(fs.readFileSync(process.env.CHART_TEST_RESPONSES, 'utf8'));
const response = responses[calls.length];
calls.push({ args: process.argv.slice(2), input: fs.readFileSync(0, 'utf8') });
fs.writeFileSync(log, JSON.stringify(calls));
if (response !== null) process.stdout.write(JSON.stringify(response));
`,
    { mode: 0o755 },
  );
  const result = spawnSync(process.execPath, [resolve('scripts/starchart-pr.mjs'), mode], {
    encoding: 'utf8',
    timeout: 10_000,
    env: {
      ...process.env,
      PATH: `${dir}:${process.env.PATH}`,
      GITHUB_REPOSITORY: options.repo,
      TARGET_BRANCH: options.base,
      GITHUB_RUN_ID: options.runId,
      GITHUB_RUN_ATTEMPT: options.attempt,
      GITHUB_REF_TYPE: 'branch',
      GITHUB_OUTPUT: output,
      CHART_BRANCH: branch,
      CHART_BASE_SHA: baseSha,
      CHART_TEST_LOG: log,
      CHART_TEST_RESPONSES: join(dir, 'responses.json'),
      ...extraEnv,
    },
  });
  return { result, output, calls: JSON.parse(readFileSync(log, 'utf8')) };
}

test('prepare CLI writes the originating attempt so failed-job reruns keep the same branch', (t) => {
  const { result, output, calls } = cli(t, 'prepare', [
    { object: { sha: baseSha } },
    { object: { sha: baseSha } },
    { object: { sha: baseSha } },
  ]);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(
    readFileSync(output, 'utf8'),
    `branch=${branch}\nbase-sha=${baseSha}\nrun-attempt=2\n`,
  );
  assert.deepEqual(JSON.parse(calls[1].input), { ref: `refs/heads/${branch}`, sha: baseSha });
});

test('publish CLI uses the preparation attempt on a rerun and verifies the URL', (t) => {
  const { result, calls } = cli(t, 'publish', publicationResponses(), {
    GITHUB_RUN_ATTEMPT: '3',
    CHART_RUN_ATTEMPT: '2',
  });
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout.trim(), 'https://github.com/CodesWhat/drydock/pull/42');
  assert.deepEqual(calls[3].args, ['api', '--method', 'POST', `${prefix}/pulls`, '--input', '-']);
});

test('publish CLI handles the empty DELETE response for unchanged charts', (t) => {
  const { result } = cli(t, 'publish', [
    { object: { sha: baseSha } },
    { status: 'identical', files: [] },
    null,
  ]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /unchanged/);
});

test('CLI refuses unknown operations before invoking GitHub', (t) => {
  const { result, calls } = cli(t, 'merge', []);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Expected prepare or publish/);
  assert.deepEqual(calls, []);
});

test('CLI rejects a tag even if its name looks like a dev branch', (t) => {
  const { result, calls } = cli(
    t,
    'prepare',
    [{ object: { sha: baseSha } }, {}, { object: { sha: baseSha } }],
    { GITHUB_REF_TYPE: 'tag' },
  );
  assert.equal(result.status, 1);
  assert.match(result.stderr, /branch dispatch/);
  assert.deepEqual(calls, []);
});

test('prepare verifies the created branch before returning outputs', async () => {
  const { api } = client([{ object: { sha: baseSha } }, {}, { object: { sha: headSha } }]);
  await assert.rejects(prepareChartBranch(api, options), /created branch/);
});
