/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default'];
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default'];
    ContainerIcon: typeof import('./src/components/ContainerIcon.vue')['default'];
    DataCardGrid: typeof import('./src/components/DataCardGrid.vue')['default'];
    DataFilterBar: typeof import('./src/components/DataFilterBar.vue')['default'];
    DataListAccordion: typeof import('./src/components/DataListAccordion.vue')['default'];
    DataTable: typeof import('./src/components/DataTable.vue')['default'];
    DataViewLayout: typeof import('./src/components/DataViewLayout.vue')['default'];
    DetailPanel: typeof import('./src/components/DetailPanel.vue')['default'];
    Dialog: typeof import('primevue/dialog')['default'];
    EmptyState: typeof import('./src/components/EmptyState.vue')['default'];
    InputText: typeof import('primevue/inputtext')['default'];
    Menu: typeof import('primevue/menu')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default'];
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default'];
  }
}
